# 开发环境配置 - 只包含与生产环境不同的配置

# 日志配置 - 开发环境详细日志
logging:
  level:
    com.ruoyi: info
    org.springframework: info
    org.springframework.web: info
    org.springframework.security: info
    org.mybatis: info
    com.alibaba.druid: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
  file:
    path: ./logs

# Spring配置 - 开发环境特定配置
spring:
  # 文件上传 - 开发环境较小限制
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  # 热部署 - 开发环境启用
  devtools:
    restart:
      enabled: true
  # Redis配置 - 开发环境连接池较小
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password: 123456
      timeout: 10s
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8
          max-wait: -1ms
  # 数据源配置 - 开发环境连接池较小
  datasource:
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://localhost:3306/ry-vue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: 123456
      # 从库数据源
      slave:
        enabled: false
      # 连接池配置
      initialSize: 5
      minIdle: 10
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置连接超时时间
      connectTimeout: 30000
      # 配置网络超时时间
      socketTimeout: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # Druid监控 - 开发环境启用
      webStatFilter: 
        enabled: true
      statViewServlet:
        enabled: true
        login-username: ruoyi
        login-password: 123456
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

# Swagger配置 - 开发环境启用
springdoc:
  swagger-ui:
    enabled: true

# 项目配置 - 开发环境
ruoyi:
  # 文件路径 - 开发环境使用本地路径
  profile: ./uploadPath
  # 获取ip地址开关 - 开发环境关闭
  addressEnabled: false

# 用户配置 - 开发环境
user:
  password:
    # 密码最大错误次数 - 开发环境较宽松
    maxRetryCount: 5
    # 密码锁定时间 - 开发环境较短
    lockTime: 10 