# 生产环境配置 - 只包含与开发环境不同的配置

# 日志配置 - 生产环境精简日志
logging:
  level:
    com.ruoyi: info
    org.springframework: warn
    org.springframework.web: warn
    org.springframework.security: warn
    org.mybatis: warn
    com.alibaba.druid: warn
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    path: ./logs

# Spring配置 - 生产环境特定配置
spring:
  # 文件上传 - 生产环境较大限制
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  # 热部署 - 生产环境禁用
  devtools:
    restart:
      enabled: false
  # Redis配置 - 生产环境连接池较大
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password: 123456
      timeout: 10s
      lettuce:
        pool:
          min-idle: 5
          max-idle: 20
          max-active: 50
          max-wait: 5000ms
  # 数据源配置 - 生产环境连接池较大
  datasource:
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://localhost:3306/ry-vue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: 123456
      # 从库数据源
      slave:
        enabled: false
      # 连接池配置
      initialSize: 10
      minIdle: 20
      maxActive: 100
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置连接超时时间
      connectTimeout: 30000
      # 配置网络超时时间
      socketTimeout: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # Druid监控 - 生产环境禁用
      webStatFilter: 
        enabled: false
      statViewServlet:
        enabled: false
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 2000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

# Swagger配置 - 生产环境禁用
springdoc:
  swagger-ui:
    enabled: false

# Token配置 - 生产环境使用复杂密钥
token:
  secret: ruoyi-vibetempt-server-production-secret-key-2025

# 项目配置 - 生产环境
ruoyi:
  # 文件路径 - 生产环境使用服务器路径
  profile: /opt/ruoyi/uploadPath
  # 获取ip地址开关 - 生产环境启用
  addressEnabled: true

# 用户配置 - 生产环境
user:
  password:
    # 密码最大错误次数 - 生产环境较严格
    maxRetryCount: 3
    # 密码锁定时间 - 生产环境较长
    lockTime: 30 